language: python

cache: pip

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - pip install .

before_script:
  - pip install -r requirements_dev.txt

script:
  - pytest -x tests
  - make check

deploy:
  provider: pypi
  user: __token__
  password:
    secure: AYDWknv/nuHAQpna2E32bxcPuu/9nX4MgsthX+6hps4YmGDWBDqfVgi0F/lwNG7SvLwxqkDcPhlG371+h6FSA0i2SUx+lF1v9PkarxWneo07Qnsqo5gbQOOUnXS7aNK7eQRfy3T/w9ZFiYfB6WARiKxywTVA4KzEzUMjLi+LNQaTijhCRhwfb/A1yREAddw/JcvL84lw7ToShxcSSGajNrgvy2T5HRIbWR47+fYJlVMKbbBYhdV7IxO92TH2j+WWk1NJcU98fCsWv6dvXk1LK5g0SrJAyi+lJxPC+LvE2LDW7RPiYaQAYbZfmulTvfPgsa9c3YqHNb1Vp2TuOHKl4FnLgHD9K9sf8x/hkke6mnOT8T53v/J96U4d2pRNvsXECrcxNyusi9Hg3LTt0AbOeKyy8gt0MqEulcph0Bcikho7iGKxX2m9CI/rLw44+8SbUoJElCDMQ87s/0C0OQW1C7RdYP6v0CHxLJ7mNdFg6xeIK28VAc6zzhIPMP+LZ3POKOcSswjfDmrjKuLYJUVr/NdloWSMbY5k56CWkZprbRnt+weokFfg9nBiwgA5+5osmR1FadzIwnul9sTo/NAoNH21iGZPfc7KHTDodrnYgqh5fiOdp0bYlVidip0wsKS4dKgXcmwsKQ9bAEf90q2kVKxsrbwwm+jSmnsfrN0gico=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
    branch: master
